import { PERMISSIONS, type Permission } from '@/constants/permissions'

export const DASHBOARD_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.ATTENDANCE_RECORD,
  PERMISSIONS.ATTENDANCE_SUMMARY_SELF,
  PERMISSIONS.ATTENDANCE_SUMMARY_ANY,
  PERMISSIONS.ATTENDANCE_VIEW_SELF,
  PERMISSIONS.ATTENDANCE_VIEW_ANY,
  PERMISSIONS.ATTENDANCE_MANAGE,
  PERMISSIONS.LEAVE_APPROVE_MANAGER,
  PERMISSIONS.LEAVE_APPROVE_HR,
  PERMISSIONS.LEAVE_REQUEST_CREATE,
  PERMISSIONS.LEAVE_REQUEST_VIEW_SELF,
  PERMISSIONS.LEAVE_REQUEST_VIEW_ASSIGNED,
  PERMISSIONS.LEAVE_REQUEST_VIEW_ANY,
  PERMISSIONS.LEAVE_BALANCE_VIEW_SELF,
  PERMISSIONS.EMPLOYEE_VIEW,
  PERMISSIONS.EMPLOYEE_VIEW_SELF,
  PERMISSIONS.EMPLOYEE_MANAGE,
  PERMISSIONS.EMPLOYEE_VIEW_ANY,
  PERMISSIONS.USER_VIEW,
]

export const ATTENDANCE_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.ATTENDANCE_RECORD,
  PERMISSIONS.ATTENDANCE_SUMMARY_SELF,
  PERMISSIONS.ATTENDANCE_SUMMARY_ANY,
  PERMISSIONS.ATTENDANCE_VIEW_SELF,
  PERMISSIONS.ATTENDANCE_VIEW_ANY,
  PERMISSIONS.ATTENDANCE_CORRECTION_REQUEST,
  PERMISSIONS.ATTENDANCE_MISSING_REQUEST,
  PERMISSIONS.ATTENDANCE_MANAGE,
  PERMISSIONS.ATTENDANCE_AUDIT_VIEW,
]

export const LEAVE_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.LEAVE_APPROVE_MANAGER,
  PERMISSIONS.LEAVE_APPROVE_HR,
  PERMISSIONS.LEAVE_REQUEST_CREATE,
  PERMISSIONS.LEAVE_REQUEST_VIEW_SELF,
  PERMISSIONS.LEAVE_REQUEST_VIEW_ASSIGNED,
  PERMISSIONS.LEAVE_REQUEST_VIEW_ANY,
  PERMISSIONS.LEAVE_BALANCE_VIEW_SELF,
]

export const OVERTIME_MY_REQUEST_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.OVERTIME_REQUEST_VIEW_SELF,
]

export const OVERTIME_APPROVAL_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.OVERTIME_APPROVE_MANAGER,
  PERMISSIONS.OVERTIME_REQUEST_VIEW_ASSIGNED,
  PERMISSIONS.OVERTIME_REQUEST_VIEW_ANY,
]

export const EMPLOYEE_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.EMPLOYEE_VIEW,
  PERMISSIONS.EMPLOYEE_MANAGE,
  PERMISSIONS.EMPLOYEE_VIEW_ANY,
]

export const USER_MANAGEMENT_ALL_PERMISSIONS: Permission[] = [
  PERMISSIONS.USER_VIEW,
  PERMISSIONS.ROLE_VIEW,
]

export const PAYROLL_RUN_ACCESS_PERMISSIONS: Permission[] = [PERMISSIONS.PAYROLL_RUN_VIEW]

export const PAYROLL_SALARY_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.PAYROLL_SALARY_VIEW,
  PERMISSIONS.PAYROLL_SALARY_MANAGE,
]

export const PAYROLL_PAYSLIP_ACCESS_PERMISSIONS: Permission[] = [
  PERMISSIONS.PAYROLL_PAYSLIP_VIEW_OWN,
]
