import { storeToRefs } from 'pinia'

import { usePayrollStore } from '../store/payrollStore'

export const usePayroll = () => {
  const payrollStore = usePayrollStore()
  const {
    payrollOwnPayslips,
    payrollSalaries,
    payrollRuns,
    payrollRunDetail,
    payrollOwnPayslipDetail,
    isPayrollOwnPayslipsLoading,
    isPayrollSalariesLoading,
    isPayrollRunsLoading,
    isPayrollRunDetailLoading,
    isPayrollOwnPayslipDetailLoading,
    isSavingPayrollSalary,
    isGeneratingPayrollRun,
    isCheckingPayrollGeneration,
    isMutatingPayrollRun,
    mutatingPayrollRunId,
    payrollRunMutationKind,
    payrollOwnPayslipsError,
    payrollSalariesError,
    payrollRunsError,
    payrollRunDetailError,
    payrollOwnPayslipDetailError,
    payrollGenerationCheckError,
    payrollGenerationMissingEmployees,
    payrollGenerationCheckMonth,
  } = storeToRefs(payrollStore)

  return {
    payrollOwnPayslips,
    payrollSalaries,
    payrollRuns,
    payrollRunDetail,
    payrollOwnPayslipDetail,
    isPayrollOwnPayslipsLoading,
    isPayrollSalariesLoading,
    isPayrollRunsLoading,
    isPayrollRunDetailLoading,
    isPayrollOwnPayslipDetailLoading,
    isSavingPayrollSalary,
    isGeneratingPayrollRun,
    isCheckingPayrollGeneration,
    isMutatingPayrollRun,
    mutatingPayrollRunId,
    payrollRunMutationKind,
    payrollOwnPayslipsError,
    payrollSalariesError,
    payrollRunsError,
    payrollRunDetailError,
    payrollOwnPayslipDetailError,
    payrollGenerationCheckError,
    payrollGenerationMissingEmployees,
    payrollGenerationCheckMonth,
    fetchPayrollOwnPayslips: payrollStore.fetchPayrollOwnPayslips,
    fetchPayrollOwnPayslipsByUrl: payrollStore.fetchPayrollOwnPayslipsByUrl,
    fetchPayrollSalaries: payrollStore.fetchPayrollSalaries,
    fetchPayrollSalariesWithFilters: payrollStore.fetchPayrollSalariesWithFilters,
    fetchPayrollSalariesByUrl: payrollStore.fetchPayrollSalariesByUrl,
    fetchPayrollRuns: payrollStore.fetchPayrollRuns,
    fetchPayrollRunsByUrl: payrollStore.fetchPayrollRunsByUrl,
    fetchPayrollOwnPayslipDetail: payrollStore.fetchPayrollOwnPayslipDetail,
    fetchPayrollRunDetail: payrollStore.fetchPayrollRunDetail,
    clearPayrollOwnPayslipDetail: payrollStore.clearPayrollOwnPayslipDetail,
    clearPayrollRunDetail: payrollStore.clearPayrollRunDetail,
    clearPayrollGenerationCheck: payrollStore.clearPayrollGenerationCheck,
    checkAndGeneratePayroll: payrollStore.checkAndGeneratePayroll,
    savePayrollSalary: payrollStore.savePayrollSalary,
    createPayrollSalary: payrollStore.createPayrollSalary,
    updatePayrollSalary: payrollStore.updatePayrollSalary,
    generatePayrollRun: payrollStore.generatePayrollRun,
    approvePayrollRun: payrollStore.approvePayrollRun,
    markPayrollRunPaid: payrollStore.markPayrollRunPaid,
    cancelPayrollRun: payrollStore.cancelPayrollRun,
    regeneratePayrollRun: payrollStore.regeneratePayrollRun,
    exportPayrollRunExcel: payrollStore.exportPayrollRunExcel,
  }
}
