/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActionMenu: typeof import('./components/ui/ActionMenu.vue')['default']
    AppSidebar: typeof import('./components/sidebar/AppSidebar.vue')['default']
    BaseBadge: typeof import('./components/ui/BaseBadge.vue')['default']
    BaseButton: typeof import('./components/ui/BaseButton.vue')['default']
    BaseCard: typeof import('./components/ui/BaseCard.vue')['default']
    BaseDatePicker: typeof import('./components/ui/BaseDatePicker.vue')['default']
    BaseDropdown: typeof import('./components/ui/BaseDropdown.vue')['default']
    BaseInput: typeof import('./components/ui/BaseInput.vue')['default']
    BaseLabel: typeof import('./components/ui/BaseLabel.vue')['default']
    BaseModal: typeof import('./components/ui/BaseModal.vue')['default']
    BaseRadioGroup: typeof import('./components/ui/BaseRadioGroup.vue')['default']
    BaseSelect: typeof import('./components/ui/BaseSelect.vue')['default']
    BaseSpinner: typeof import('./components/ui/BaseSpinner.vue')['default']
    BaseTable: typeof import('./components/ui/BaseTable.vue')['default']
    BaseTextarea: typeof import('./components/ui/BaseTextarea.vue')['default']
    BaseTimePicker: typeof import('./components/ui/BaseTimePicker.vue')['default']
    ConfirmActionModal: typeof import('./components/ui/ConfirmActionModal.vue')['default']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPagination: typeof import('element-plus/es')['ElPagination']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTimePicker: typeof import('element-plus/es')['ElTimePicker']
    HelloWorld: typeof import('./components/HelloWorld.vue')['default']
    IconCommunity: typeof import('./components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./components/icons/IconEcosystem.vue')['default']
    IconSupport: typeof import('./components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./components/icons/IconTooling.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TheWelcome: typeof import('./components/TheWelcome.vue')['default']
    WelcomeItem: typeof import('./components/WelcomeItem.vue')['default']
  }
  export interface GlobalDirectives {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
